export const GET_SEARCHED_PHOTOS_SUCCESS = "GET_SEARCHED_PHOTOS_SUCCESS";
export const GET_SEARCHED_PHOTOS_PENDING = "GET_SEARCHED_PHOTOS_PENDING";
export const GET_SEARCHED_PHOTOS_ERROR = "GET_SEARCHED_PHOTOS_ERROR";
